### ISSUE TITLE
Support for Laravel 5.x

### ISSUE THREAD

**Issue by albabar** [BKWLD/upchuck#5]
The package looks cool to me.
I wanted to use it for one of me project. Unfortunately it doesn't have Laravel 5.x support.
Can you please fix the issue?

**Comment by weotch** [comment]
Yeah, I imagine I'll be addressing this sometime in the next 30 days.  Sorry it's not sooner.

**Comment by albabar** [comment]
Thanks. :)

**Comment by weotch** [comment]
This work is in the 2.0 branch now
