### ISSUE TITLE
composer require bkwld/upchuck:~2.0

### ISSUE THREAD

**Issue by micahaza** [BKWLD/upchuck#7]
I've just tried to install upchuck for LR5 and it failed:

  Problem 1
    - The requested package bkwld/upchuck could not be found in any version, there may be a typo in the package name.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see https://getcomposer.org/doc/04-schema.md#minimum-stability for more details.

Read https://getcomposer.org/doc/articles/troubleshooting.md for further common problems.

Do I need to run composer require bkwld/upchuck:2.0.x-dev instead?

bash$ composer show bkwld/upchuck
name     : bkwld/upchuck
descrip. : A simple, automatic handler of file uploads for Laravel's Eloquent models using using Flysystem.
keywords : 
versions : dev-master, \* 2.0.x-dev, 1.1.4, 1.1.3, 1.1.2, 1.1.1, 1.1.0, 1.0.0

**Comment by weotch** [comment]
Yeah, use `2.0.x-dev`

You may need to change your `minimum-stability` to `dev` too
