### ISSUE TITLE
Support Laravel 5.4

### ISSUE THREAD

**Issue by weotch** [BKWLD/upchuck#9]
It has removed event priorities

> Support for event handler "priorities" has been removed. This undocumented feature typically indicates an abuse of the event feature. Instead, consider using a series of synchronous method calls. Alternatively, you may dispatch a new event from within the handler of another event in order to ensure that a given event's handler fires after an unrelated handler.

I think re-dispatching an event like described here is the right course of action.

**Comment by weotch** [comment]
So upchuck will fire an event after it's done.  Other libraries, like https://github.com/BKWLD/decoy, will listen to that rather than the eloquent events.

Also, in [this case](https://github.com/BKWLD/decoy/blob/7f5b767c41a912072615349cb68c2dca394fc4ee/classes/Models/Image.php#L115-L120) maybe the Decoy method can read the original `UploadFile` instance from a different property ... like raw arttributes?  

If not, lets have Uphuck store references to the things it changed in it's own property that decoy can read.  Like the `SupportsUpload` trait has a `mutatedByUpchuck` array with keys that are model attributes and values being the original `UploadFile` attributes.

**Comment by brokenhd** [comment]
So far, this hasn't been an issue in L5.4
